spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/health_sync_test?serverTimezone=UTC&characterEncoding=UTF-8
    username: health_sync
    password: health_sync
  flyway:
    baseline-on-migrate: true
    url: jdbc:mysql://127.0.0.1:3306/health_sync_test?serverTimezone=UTC&characterEncoding=UTF-8
    baseline-version: 1
    user: health_sync
    password: health_sync
    enabled: true
    locations: classpath:db/migration
    schemas: health_sync_test
    clean-disabled: false

  jpa:
    hibernate:
      ddl-auto: create